customprop:
  test: 12345
spring:
  zipkin:
    base-url: http://hexadb:9411/
  cloud:
    compatibility-verifier:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9900
  log:
    level: info
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    #  naming:
    #    implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    #    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  redis:
    data:
      host: db
      port: 6379
      database: hexadb
      repositories:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekahost:8761/eureka}
custom:
  security:
    expose-unsecured-urls: true
    unsecured-urls:
      - cancel-reasons/**
      - /operator/
      - /captain**
management:
  zipkin:
    tracing:
      endpoint: http://hexadb:9411/api/v2/spans  
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
